# Generated by Django 3.1.2 on 2020-10-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20201009_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_marketing_promociona',
            new_name='preco_marketing_promocional',
        ),
    ]
