# Generated by Django 3.1.2 on 2020-10-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20201009_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
